query AllCycle {
  allCycle {
    action
    id
    createdAt
    beginDate
    finishDate
    valueBTC
    valueUSD
    finalValueUSD
    finalValueBTC
    hash
    state
    beginDate
    userId
  }
}
