import { Box } from '@chakra-ui/react';
import Head from 'next/head';

const Login = () =>{
	return(
		<Box bg='tomato' w='100%' p={4} color='white'>
			<Head>
				<title>Login</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>


		</Box>
	);
};

export default Login;